[DO NOT MERGE]Training DLC for Pytorch 1.10
aws/deep-learning-containers pull request #1392
Opened 2021-10-01 22:55 UTC by waytrue17

*GitHub Issue #, if available:*

Note: If merging this PR should also close the associated Issue, please also add that Issue # to the Linked Issues section on the right. 

### Description

### Tests run
**NOTE: If you are creating a PR for a new framework version, please ensure success of the standard, rc, and efa sagemaker remote tests by updating the dlc_developer_config.toml file:**

- [ ] Revision A: `sagemaker_remote_tests = "standard"`
- [ ] Revision B: `sagemaker_remote_tests = "rc"`
- [ ] Revision C: `sagemaker_remote_tests = "efa"`

**Additionally, please run the sagemaker local tests in at least one revision:**
- [ ] `sagemaker_local_tests = true`

### DLC image/dockerfile

### Additional context

## Label Checklist
- [ ] I have added the project label for this PR (*<project_name>* or "Improvement")

## PR Checklist
- [ ] I've prepended PR tag with frameworks/job this applies to : [mxnet, tensorflow, pytorch] | [ei/neuron/graviton] | [build] | [test] | [benchmark] | [ec2, ecs, eks, sagemaker]
- [ ] If the PR changes affects SM test, I've modified dlc_developer_config.toml in my PR branch by setting sagemaker_tests = true and efa_tests = true
- [ ] If this PR changes existing code, the change fully backward compatible with pre-existing code. (Non backward-compatible changes need special approval.)
- [ ] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [ ] (If applicable) I've documented below the tests I've run on the DLC image
- [ ] (If applicable) I've reviewed the licenses of updated and new binaries and their dependencies to make sure all licenses are on the Apache Software Foundation Third Party License Policy Category A or Category B license list.  See [https://www.apache.org/legal/resolved.html](https://www.apache.org/legal/resolved.html).
- [ ] (If applicable) I've scanned the updated and new binaries to make sure they do not have vulnerabilities associated with them.

## Pytest Marker Checklist
- [ ] (If applicable) I have added the marker `@pytest.mark.model("<model-type>")` to the new tests which I have added, to specify the Deep Learning model that is used in the test (use `"N/A"` if the test doesn't use a model)
- [ ] (If applicable) I have added the marker `@pytest.mark.integration("<feature-being-tested>")` to the new tests which I have added, to specify the feature that will be tested
- [ ] (If applicable) I have added the marker `@pytest.mark.multinode(<integer-num-nodes>)` to the new tests which I have added, to specify the number of nodes used on a multi-node test
- [ ] (If applicable) I have added the marker `@pytest.mark.processor(<"cpu"/"gpu"/"eia"/"neuron"/"graviton">)` to the new tests which I have added, if a test is specifically applicable to only one processor type

#### EIA/NEURON/GRAVITON Testing Checklist
* When creating a PR:
- [ ] I've modified `dlc_developer_config.toml` in my PR branch by setting `ei_mode = true`, `neuron_mode = true` or `graviton_mode = true`

#### Benchmark Testing Checklist
* When creating a PR:
- [ ] I've modified `dlc_developer_config.toml` in my PR branch by setting `benchmark_mode = true`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-10-05 06:03 UTC, arjkesh commented
@waytrue17 - the EC2 NCCL tests seem to be failing on the gpu training image.

There are also some pip check and torch vision failures in the sanity tests - these seem to be related to the fact that we don't have a TV version that supports PT1.10 yet

2021-10-05 06:06 UTC, arjkesh commented on pytorch/training/docker/1.10/py3/Dockerfile.diy.cpu
> +# Copy workaround script for incorrect hostname
this looks specific to SM images - we can prob move this along with the custom entrypoint to the SM image as a result

2021-10-05 06:06 UTC, arjkesh commented on pytorch/training/docker/1.10/py3/cu113/Dockerfile.diy.gpu
> +COPY changehostname.c /
this looks specific to SM images - we can prob move this along with the custom entrypoint to the SM image as a result

2021-10-05 07:31 UTC, arjkesh requested changes

2021-10-05 07:31 UTC, arjkesh commented on test/dlc_tests/ec2/pytorch/training/test_pytorch_training.py
> +@pytest.mark.skip(reason="Skip DGL tests for PT1.10, since there is no compatible version at the moment")
unskip or conditionally skip before merge

2021-10-05 07:31 UTC, arjkesh commented on test/dlc_tests/ecs/pytorch/training/test_ecs_pytorch_training.py
> +@pytest.mark.skip(reason="Skip DGL tests for PT1.10, since there is no compatible version at the moment")
unskip or conditionally skip before merge

2021-10-05 07:31 UTC, arjkesh commented on test/dlc_tests/ecs/pytorch/training/test_ecs_pytorch_training.py
> +@pytest.mark.skip(reason="Skip DGL tests for PT1.10, since there is no compatible version at the moment")
unskip or conditionally skip before merge

2021-10-05 07:31 UTC, arjkesh commented on test/dlc_tests/eks/pytorch/training/test_eks_pytorch_training.py
> +@pytest.mark.skip(reason="Skip DGL tests for PT1.10, since there is no compatible version at the moment")
unskip or conditionally skip before merge

2021-11-15 03:29 UTC, Kyeongpil commented
Is there any progress? I want to know when we can use the Pytorch 1.10 container on Sagemaker.

2021-11-22 22:49 UTC, waytrue17 commented
Close this PR as it was addressed in other PRs

2021-11-22 22:49 UTC, closed without merging

2021-11-22 22:59 UTC, waytrue17 commented
> Hi, @waytrue17. Is there any progress? I want to know when we can use the Pytorch 1.10 container on Sagemaker.

Hi Kyeongpil, the PT 1.10 DLC effort has been done in other PRs #1459 #1482. I think it will come soon as our team is actively pushing the release