[tensorflow] [trcomp] [huggingface] add trcomp 2.6 dockerfile with latest CVE fixes
aws/deep-learning-containers pull request #2028
Opened 2022-06-16 02:26 UTC by codeislife99

*GitHub Issue #, if available:*

Note: If merging this PR should also close the associated Issue, please also add that Issue # to the Linked Issues section on the right. 

### Description

### Tests run
**NOTE: If you are creating a PR for a new framework version, please ensure success of the standard, rc, and efa sagemaker remote tests by updating the dlc_developer_config.toml file:**

- [ ] Revision A: `sagemaker_remote_tests = "standard"`
- [ ] Revision B: `sagemaker_remote_tests = "rc"`
- [ ] Revision C: `sagemaker_remote_tests = "efa"`

**Additionally, please run the sagemaker local tests in at least one revision:**
- [ ] `sagemaker_local_tests = true`

### DLC image/dockerfile

### Additional context

## Label Checklist
- [ ] I have added the project label for this PR (*<project_name>* or "Improvement")

## PR Checklist
- [ ] I've prepended PR tag with frameworks/job this applies to : [mxnet, tensorflow, pytorch] | [ei/neuron/graviton] | [build] | [test] | [benchmark] | [ec2, ecs, eks, sagemaker]
- [ ] If the PR changes affects SM test, I've modified dlc_developer_config.toml in my PR branch by setting sagemaker_tests = true and efa_tests = true
- [ ] If this PR changes existing code, the change fully backward compatible with pre-existing code. (Non backward-compatible changes need special approval.)
- [ ] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [ ] (If applicable) I've documented below the tests I've run on the DLC image
- [ ] (If applicable) I've reviewed the licenses of updated and new binaries and their dependencies to make sure all licenses are on the Apache Software Foundation Third Party License Policy Category A or Category B license list.  See [https://www.apache.org/legal/resolved.html](https://www.apache.org/legal/resolved.html).
- [ ] (If applicable) I've scanned the updated and new binaries to make sure they do not have vulnerabilities associated with them.

## Pytest Marker Checklist
- [ ] (If applicable) I have added the marker `@pytest.mark.model("<model-type>")` to the new tests which I have added, to specify the Deep Learning model that is used in the test (use `"N/A"` if the test doesn't use a model)
- [ ] (If applicable) I have added the marker `@pytest.mark.integration("<feature-being-tested>")` to the new tests which I have added, to specify the feature that will be tested
- [ ] (If applicable) I have added the marker `@pytest.mark.multinode(<integer-num-nodes>)` to the new tests which I have added, to specify the number of nodes used on a multi-node test
- [ ] (If applicable) I have added the marker `@pytest.mark.processor(<"cpu"/"gpu"/"eia"/"neuron">)` to the new tests which I have added, if a test is specifically applicable to only one processor type

#### EIA/NEURON/GRAVITON Testing Checklist
* When creating a PR:
- [ ] I've modified `dlc_developer_config.toml` in my PR branch by setting `ei_mode = true`, `neuron_mode = true` or `graviton_mode = true`

#### Benchmark Testing Checklist
* When creating a PR:
- [ ] I've modified `dlc_developer_config.toml` in my PR branch by setting `benchmark_mode = true`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-06-16 16:01 UTC, Lokiiiiii commented
@tejaschumbalkar  Could you please check why the tests are blocked ?

2022-06-16 17:03 UTC, tejaschumbalkar commented
> @tejaschumbalkar Could you please check why the tests are blocked ?

Please add @codeislife99 to dlc-trcomp-reviewers

2022-06-16 22:28 UTC, codeislife99 commented
The CI is failing because the numpy version and some other things are not changed in the base image.

2022-06-16 22:45 UTC, codeislife99 commented
The CI seems to be failing because of Opencv & numpy vulnerabilities in the base image. THey are still 4.5.5 and 1.19 respectively.

2022-06-19 02:02 UTC, Lokiiiiii requested changes

2022-06-19 02:02 UTC, Lokiiiiii commented on huggingface/tensorflow/training/docker/2.6/py3/cu112/Dockerfile.trcomp.gpu
>      "typing-extensions==3.7.4.3" \
```suggestion
    "typing-extensions==3.7.4.3"
```

2022-06-24 16:13 UTC, tejaschumbalkar commented
/rerun

2022-06-30 17:28 UTC, Lokiiiiii submitted a review, later dismissed

2022-07-01 17:47 UTC, codeislife99 commented
/rerun

2022-07-01 21:55 UTC, codeislife99 commented
@tejaschumbalkar - Many of the tests are failing because of capacity errors and because of vulnerabilities in the base image. What is the recommended solution here ?

2022-07-05 18:09 UTC, saimidu commented
@codeislife99 As of now, the only solution is to rerun the tests. All the tests that previously succeeded are not going to be rerun the next time.

2022-07-05 18:37 UTC, codeislife99 commented
/rerun  dlc-pr-ec2-test

2022-07-06 17:36 UTC, tejaschumbalkar commented on huggingface/tensorflow/training/docker/2.6/py3/cu112/Dockerfile.trcomp.gpu
>      "typing-extensions==3.7.4.3" \
Why is this package pinned?

2022-07-07 18:10 UTC, Qingzi-Lan commented
tests passed on commit [065a13d]

2022-07-07 22:03 UTC, codeislife99 commented
@saimidu @Lokiiiiii Can I get a final thumbs up for merge , all tests have passed in previous commit and I reverted the dlc_developer_config file.

2022-07-08 22:22 UTC, tejaschumbalkar approved these changes

2022-07-08 22:23 UTC, tejaschumbalkar commented
@Lokiiiiii Can you review/approve the PR?

2022-07-09 00:29 UTC, Lokiiiiii approved these changes

2022-07-09 01:05 UTC, codeislife99 commented
Can we merge this PR now ? All tests have already passed in a previous similar commit

2022-07-11 18:05 UTC, merged