[trcomp] [huggingface_tensorflow] [build] Adding support for TF 2.8
aws/deep-learning-containers pull request #2031
Opened 2022-06-17 02:27 UTC by codeislife99

*GitHub Issue #, if available:*

Note: If merging this PR should also close the associated Issue, please also add that Issue # to the Linked Issues section on the right. 

### Description

### Tests run
**NOTE: If you are creating a PR for a new framework version, please ensure success of the standard, rc, and efa sagemaker remote tests by updating the dlc_developer_config.toml file:**

- [ ] Revision A: `sagemaker_remote_tests = "standard"`
- [ ] Revision B: `sagemaker_remote_tests = "rc"`
- [ ] Revision C: `sagemaker_remote_tests = "efa"`

**Additionally, please run the sagemaker local tests in at least one revision:**
- [ ] `sagemaker_local_tests = true`

### DLC image/dockerfile

### Additional context

## Label Checklist
- [ ] I have added the project label for this PR (*<project_name>* or "Improvement")

## PR Checklist
- [ ] I've prepended PR tag with frameworks/job this applies to : [mxnet, tensorflow, pytorch] | [ei/neuron/graviton] | [build] | [test] | [benchmark] | [ec2, ecs, eks, sagemaker]
- [ ] If the PR changes affects SM test, I've modified dlc_developer_config.toml in my PR branch by setting sagemaker_tests = true and efa_tests = true
- [ ] If this PR changes existing code, the change fully backward compatible with pre-existing code. (Non backward-compatible changes need special approval.)
- [ ] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [ ] (If applicable) I've documented below the tests I've run on the DLC image
- [ ] (If applicable) I've reviewed the licenses of updated and new binaries and their dependencies to make sure all licenses are on the Apache Software Foundation Third Party License Policy Category A or Category B license list.  See [https://www.apache.org/legal/resolved.html](https://www.apache.org/legal/resolved.html).
- [ ] (If applicable) I've scanned the updated and new binaries to make sure they do not have vulnerabilities associated with them.

## Pytest Marker Checklist
- [ ] (If applicable) I have added the marker `@pytest.mark.model("<model-type>")` to the new tests which I have added, to specify the Deep Learning model that is used in the test (use `"N/A"` if the test doesn't use a model)
- [ ] (If applicable) I have added the marker `@pytest.mark.integration("<feature-being-tested>")` to the new tests which I have added, to specify the feature that will be tested
- [ ] (If applicable) I have added the marker `@pytest.mark.multinode(<integer-num-nodes>)` to the new tests which I have added, to specify the number of nodes used on a multi-node test
- [ ] (If applicable) I have added the marker `@pytest.mark.processor(<"cpu"/"gpu"/"eia"/"neuron">)` to the new tests which I have added, if a test is specifically applicable to only one processor type

#### EIA/NEURON/GRAVITON Testing Checklist
* When creating a PR:
- [ ] I've modified `dlc_developer_config.toml` in my PR branch by setting `ei_mode = true`, `neuron_mode = true` or `graviton_mode = true`

#### Benchmark Testing Checklist
* When creating a PR:
- [ ] I've modified `dlc_developer_config.toml` in my PR branch by setting `benchmark_mode = true`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-06-19 02:10 UTC, Lokiiiiii requested changes

2022-06-19 02:10 UTC, Lokiiiiii commented on huggingface/tensorflow/buildspec-trcomp.yml
>      tag_python_version: &TAG_PYTHON_VERSION py38
```suggestion
    tag_python_version: &TAG_PYTHON_VERSION py39
```

2022-06-19 02:10 UTC, Lokiiiiii commented on huggingface/tensorflow/training/docker/2.8/py3/cu112/Dockerfile.trcomp.gpu
> +FROM 763104351884.dkr.ecr.us-west-2.amazonaws.com/tensorflow-training:2.8.0-gpu-py39-cu112-ubuntu20.04-sagemaker
```suggestion
FROM 763104351884.dkr.ecr.us-west-2.amazonaws.com/tensorflow-training:2.8-gpu-py39-cu112-ubuntu20.04-sagemaker
```

2022-06-19 02:10 UTC, Lokiiiiii commented on huggingface/tensorflow/training/docker/2.8/py3/cu112/Dockerfile.trcomp.gpu
> +# version args
```suggestion
# Version args can be overwritten by buildspec args
```

2022-06-19 02:10 UTC, Lokiiiiii commented on huggingface/tensorflow/training/docker/2.8/py3/cu112/Dockerfile.trcomp.gpu
> +    transformers[sklearn,sentencepiece]==${TRANSFORMERS_VERSION} \
```suggestion
    transformers[sklearn,sentencepiece,audio,vision]==${TRANSFORMERS_VERSION} \
```

2022-06-19 02:10 UTC, Lokiiiiii commented on huggingface/tensorflow/training/docker/2.8/py3/cu112/Dockerfile.trcomp.gpu
> +    # TODO: Remove upgrade statements once packages are updated in base image
These should be fixed by now

2022-06-19 02:10 UTC, Lokiiiiii commented on huggingface/tensorflow/training/docker/2.8/py3/cu112/Dockerfile.trcomp.gpu
> +ARG TF_URL="https://framework-binaries.s3.us-west-2.amazonaws.com/tensorflow/hopper/r2.8_aws/gpu/2022-04-20-19-24/tensorflow_gpu-2.8.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2
Remove codeword names

2023-03-22 06:27 UTC, tejaschumbalkar commented
TF 2.8 is out of support

2023-03-22 20:45 UTC, closed without merging