[PT2.0.1][CUDA12] remove keys
aws/deep-learning-containers pull request #3306
Opened 2023-09-06 00:05 UTC by jeet4320

*GitHub Issue #, if available:*

**Note**: 
- If merging this PR should also close the associated Issue, please also add that Issue # to the Linked Issues section on the right. 

- All PR's are checked weekly for staleness. This PR will be closed if not updated in 30 days.

### Description

### Tests run

**NOTE: By default, docker builds are disabled. In order to build your container, please update dlc_developer_config.toml and specify the framework to build in "build_frameworks"**
- [ ] I have run builds/tests on commit <INSERT COMMIT ID> for my changes.

**NOTE: If you are creating a PR for a new framework version, please ensure success of the standard, rc, and efa sagemaker remote tests by updating the dlc_developer_config.toml file:**

- [ ] Revision A: `sagemaker_remote_tests = "standard"`
- [ ] Revision B: `sagemaker_remote_tests = "rc"`
- [ ] Revision C: `sagemaker_remote_tests = "efa"`

**Additionally, please run the sagemaker local tests in at least one revision:**
- [ ] `sagemaker_local_tests = true`

### Formatting
- [ ] I have run `black -l 100` on my code (formatting tool: https://black.readthedocs.io/en/stable/getting_started.html)

### DLC image/dockerfile

### Additional context

## PR Checklist
- [ ] I've prepended PR tag with frameworks/job this applies to : [mxnet, tensorflow, pytorch] | [ei/neuron/graviton] | [build] | [test] | [benchmark] | [ec2, ecs, eks, sagemaker]
- [ ] If the PR changes affects SM test, I've modified dlc_developer_config.toml in my PR branch by setting sagemaker_tests = true and efa_tests = true
- [ ] If this PR changes existing code, the change fully backward compatible with pre-existing code. (Non backward-compatible changes need special approval.)
- [ ] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [ ] (If applicable) I've documented below the tests I've run on the DLC image
- [ ] (If applicable) I've reviewed the licenses of updated and new binaries and their dependencies to make sure all licenses are on the Apache Software Foundation Third Party License Policy Category A or Category B license list.  See [https://www.apache.org/legal/resolved.html](https://www.apache.org/legal/resolved.html).
- [ ] (If applicable) I've scanned the updated and new binaries to make sure they do not have vulnerabilities associated with them.

## Pytest Marker Checklist
- [ ] (If applicable) I have added the marker `@pytest.mark.model("<model-type>")` to the new tests which I have added, to specify the Deep Learning model that is used in the test (use `"N/A"` if the test doesn't use a model)
- [ ] (If applicable) I have added the marker `@pytest.mark.integration("<feature-being-tested>")` to the new tests which I have added, to specify the feature that will be tested
- [ ] (If applicable) I have added the marker `@pytest.mark.multinode(<integer-num-nodes>)` to the new tests which I have added, to specify the number of nodes used on a multi-node test
- [ ] (If applicable) I have added the marker `@pytest.mark.processor(<"cpu"/"gpu"/"eia"/"neuron">)` to the new tests which I have added, if a test is specifically applicable to only one processor type

#### EIA/NEURON/GRAVITON Testing Checklist
* When creating a PR:
- [ ] I've modified `dlc_developer_config.toml` in my PR branch by setting `ei_mode = true`, `neuron_mode = true` or `graviton_mode = true`

#### Benchmark Testing Checklist
* When creating a PR:
- [ ] I've modified `dlc_developer_config.toml` in my PR branch by setting `benchmark_mode = true`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-09-06 16:50 UTC, jeet4320 commented
All tests passed except sanity ECR scan.

2023-09-06 21:52 UTC, ohadkatz approved these changes

2023-09-06 21:54 UTC, ohadkatz requested changes
Please revert TOML and update branch

2023-09-06 21:55 UTC, saimidu commented
The EC2 tests timed out in [5459ceb](https://github.com/aws/deep-learning-containers/pull/3306/commits/5459ceb308ca08d3360a672cc591f2e789172661)

2023-09-06 23:17 UTC, saimidu commented
`test_pytorch_training_torchdata_gpu` fails due to `pytest not found`.

2023-09-06 23:36 UTC, jeet4320 commented
> `test_pytorch_training_torchdata_gpu` fails due to `pytest not found`.

Yes retrying it. Have update PR body with commit and its tests status. There is no change on that test

2023-09-07 00:06 UTC, jeet4320 commented
> > `test_pytorch_training_torchdata_gpu` fails due to `pytest not found`.
> 
> Yes retrying it. Have update PR body with commit and its tests status. There is no change on that test

still same error, I see we are installing pytest but https://github.com/aws/deep-learning-containers/blob/master/test/dlc_tests/container_tests/bin/pytorch_tests/testTorchdata#L22

2023-09-07 20:32 UTC, jeet4320 commented
Getting ECR pull error for 3 continuous runs. Will retry in few hours

2023-09-07 22:19 UTC, jeet4320 commented on test/testrunner.py
>          pytest_cmd = ["-s", "-rA", test_path, f"--junitxml={report}", "-n=auto"]
to be reverted

2023-09-07 22:57 UTC, saimidu commented on pytorch/training/buildspec.yml
> +  #   <<: *TRAINING_REPOSITORY
Will this change be reverted?

2023-09-07 22:58 UTC, saimidu reviewed
Approved. Please revert temporary changes.

2023-09-07 23:06 UTC, saimidu approved these changes

2023-09-07 23:24 UTC, merged