[pytorch] Add team marker for pytorch tests
aws/deep-learning-containers pull request #3405
Opened 2023-10-18 04:17 UTC by tejaschumbalkar

*GitHub Issue #, if available:*

**Note**: 
- If merging this PR should also close the associated Issue, please also add that Issue # to the Linked Issues section on the right. 

- All PR's are checked weekly for staleness. This PR will be closed if not updated in 30 days.

### Description

Add team markers for pytorch tests

### Tests run

**NOTE: By default, docker builds are disabled. In order to build your container, please update dlc_developer_config.toml and specify the framework to build in "build_frameworks"**
- [ ] I have run builds/tests on commit <INSERT COMMIT ID> for my changes.

**NOTE: If you are creating a PR for a new framework version, please ensure success of the standard, rc, and efa sagemaker remote tests by updating the dlc_developer_config.toml file:**

- [ ] Revision A: `sagemaker_remote_tests = "standard"`
- [ ] Revision B: `sagemaker_remote_tests = "rc"`
- [ ] Revision C: `sagemaker_remote_tests = "efa"`

**Additionally, please run the sagemaker local tests in at least one revision:**
- [ ] `sagemaker_local_tests = true`

### Formatting
- [ ] I have run `black -l 100` on my code (formatting tool: https://black.readthedocs.io/en/stable/getting_started.html)

### DLC image/dockerfile

### Additional context

## PR Checklist
- [ ] I've prepended PR tag with frameworks/job this applies to : [mxnet, tensorflow, pytorch] | [ei/neuron/graviton] | [build] | [test] | [benchmark] | [ec2, ecs, eks, sagemaker]
- [ ] If the PR changes affects SM test, I've modified dlc_developer_config.toml in my PR branch by setting sagemaker_tests = true and efa_tests = true
- [ ] If this PR changes existing code, the change fully backward compatible with pre-existing code. (Non backward-compatible changes need special approval.)
- [ ] (If applicable) I've documented below the DLC image/dockerfile this relates to
- [ ] (If applicable) I've documented below the tests I've run on the DLC image
- [ ] (If applicable) I've reviewed the licenses of updated and new binaries and their dependencies to make sure all licenses are on the Apache Software Foundation Third Party License Policy Category A or Category B license list.  See [https://www.apache.org/legal/resolved.html](https://www.apache.org/legal/resolved.html).
- [ ] (If applicable) I've scanned the updated and new binaries to make sure they do not have vulnerabilities associated with them.

## Pytest Marker Checklist
- [ ] (If applicable) I have added the marker `@pytest.mark.model("<model-type>")` to the new tests which I have added, to specify the Deep Learning model that is used in the test (use `"N/A"` if the test doesn't use a model)
- [ ] (If applicable) I have added the marker `@pytest.mark.integration("<feature-being-tested>")` to the new tests which I have added, to specify the feature that will be tested
- [ ] (If applicable) I have added the marker `@pytest.mark.multinode(<integer-num-nodes>)` to the new tests which I have added, to specify the number of nodes used on a multi-node test
- [ ] (If applicable) I have added the marker `@pytest.mark.processor(<"cpu"/"gpu"/"eia"/"neuron">)` to the new tests which I have added, if a test is specifically applicable to only one processor type

#### EIA/NEURON/GRAVITON Testing Checklist
* When creating a PR:
- [ ] I've modified `dlc_developer_config.toml` in my PR branch by setting `ei_mode = true`, `neuron_mode = true` or `graviton_mode = true`

#### Benchmark Testing Checklist
* When creating a PR:
- [ ] I've modified `dlc_developer_config.toml` in my PR branch by setting `benchmark_mode = true`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-10-25 19:24 UTC, roywei requested changes
Thanks for going through these tests, let's redirect inductor, graviton and dgl tests, rest LGTM

2023-10-25 19:24 UTC, roywei commented on test/dlc_tests/eks/pytorch/training/test_eks_pytorch_training.py
> +@pytest.mark.team("conda")
should this go to DGL team?

2023-10-25 19:24 UTC, roywei commented on test/sagemaker_tests/pytorch/training/integration/sagemaker/test_dgl.py
> +@pytest.mark.team("conda")
DGL team

2023-10-26 04:52 UTC, tejaschumbalkar commented
- Removed the ownership for graviton, dgl and inductor test.
- Changed the github team in codeowners

2023-10-26 04:53 UTC, tejaschumbalkar commented on test/dlc_tests/benchmark/ec2/pytorch/inference/test_performance_pytorch_inference.py
> +@pytest.mark.team("conda")
addressed

2023-10-26 04:53 UTC, tejaschumbalkar commented on test/dlc_tests/benchmark/ec2/pytorch/training/test_performance_pytorch_training.py
> +@pytest.mark.team("conda")
addressed

2023-10-26 04:53 UTC, tejaschumbalkar commented on test/dlc_tests/benchmark/sagemaker/pytorch/training/test_performance_inductor.py
> +@pytest.mark.team("conda")
addressed

2023-10-26 04:53 UTC, tejaschumbalkar commented on test/dlc_tests/eks/pytorch/training/test_eks_pytorch_training.py
> +@pytest.mark.team("conda")
addressed

2023-10-26 04:53 UTC, tejaschumbalkar commented on test/sagemaker_tests/pytorch/training/integration/sagemaker/test_dgl.py
> +@pytest.mark.team("conda")
addressed

2023-10-26 20:00 UTC, junpuf requested changes
Found some more inductor tests to be re-linked

2023-10-26 20:14 UTC, tejaschumbalkar commented on test/dlc_tests/ec2/pytorch/training/test_pytorch_training.py
>  def test_pytorch_nccl_inductor(
done

2023-10-26 20:14 UTC, tejaschumbalkar commented on test/sagemaker_tests/pytorch/inference/integration/sagemaker/test_mnist_inductor.py
> +@pytest.mark.team("conda")
done

2023-10-26 20:27 UTC, roywei approved these changes
LGTM!

2023-10-26 20:28 UTC, junpuf approved these changes
LGTM

2023-10-26 20:44 UTC, merged